language: node_js
version: '~> 1.0.0'
node_js:
  - 14.17.0
cache: yarn
jobs:
  include:
    - stage: npm-bundle
      script: yarn build && npm version $TRAVIS_BRANCH --allow-same-version --allow-empty
      deploy:
        edge: true
        provider: npm
        email: bameyrick@gmail.com
        api_token:
          secure: o9BBFb7Mv+nuVOt+WxS4ohWhCN/Pawria1q8IiZaOStl5SxIod3G0uCzYD8kK87qClTe20HkBAjxkrso7DTmMlLiNLIaKckxxsLO/JQkJDAyHhaArUxqVEcs6hIGDBbDJijm6+0dcqYaLbIEp0YszHM5mpdc51tTrPPxDCNifkC1RXoZ+T9igKGy+ymj/ED/8mGUqvo2g7Kuw5cSkCoBK3AUgOd19J4RFa+sUa+/JqxZHZh7TrCbtuytptCJN0RJQvMarnRKY/U2W7H0FCECsOF3lNaeJ9H6nlEQ6vx5XNIKnuiAWYjkvo/MGMJMYv81JNT7gKQFdfdepaCr2TGApoJv3UrGbsvYZ4e5Z2Tw3XvV9Irbb/+7dLgqcfA9/gnPJ72X8cC0vc4kV6OWuApmNeR4qGFspx3a1s6Xz40YodrfY0VuGGyQRgyDhKHxDfbSLP2oK1aH824hKEDzr4IPUcDYaQ0aO4ivmT+5w1ZOi2or9NQ8XKrNUg61e29fKjqJwDy3DARxNnDppjZpGdY9DI0c44I3zgJm1YzUWzIoCihV9eUoStzmYo4XYROlwFJV/074IS4+ekgO3SUpTAfrjDi6wZMLtJoJdvLlZLxY+4nXQ0XVbh5zUMZHzmKEk3szIBkKXiOgwS5Ccd9+GPf9FgPXBmFen5hP19giug0ECao=
        on:
          tags: true
stages:
  - name: npm-bundle
    if: tag IS present
